### ISSUE TITLE
Discord emotes info missing

### ISSUE THREAD

**Issue by lukynmatuska** [ondryaso/kachna-online#113]
Please add small info how to use Discord emotes when changing state of student club. (url: `/kachna/states/change`)

Thanks. :peepolove:
![image](https://user-images.githubusercontent.com/19732513/158788227-5d8dc6b1-a7cb-4c55-ae2a-add68883fedb.png)

**Comment by ondryaso** [comment]
I will not add info about using Discord emotes in messages that are not only sent to Discord but also shown at the page and possibly other places, where having `<:name:64b-long-number:>` would look silly. Feel free to open an issue with formatting of messages in general. I never planned the messages to be anything more than plaintext but they could certainly be formatted with Markdown but that would require new backend codebase to process them differently at the endpoints (I'm thinking of a `plaintext` request parameter that would strip the message of any formatting) and the notifications; and implementing that in the frontend, obviously (however, there's a Markdown library for Angular, so that would be fairly easy).
